var GAME_LEVELS = [
  ["                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                               ",
   "                                                 xxxxxxxxxxxxxx",
   "                         o o o o                 xo           x",
   "                        o o o o o                x            x",
   "  @   s                  o o o o                 x       #^   x",
   "xxxxxxxx              xxxxxxxxxxxxx              x   xxxxxxxxxx",
   "xxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxx              xx  xxxxxxxxxx",
   "xxxxxxxx!!!!!!!!!!!!!!xx   |                         xxxxxxxxxx",
   "xxxxxxxx!!!!!!!!!!!!!!xx=       | =x                 xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
	
  ["                                                                                                                                            ",
   "                 oooo                oooo                oooo                oooo                oooo               oooo                    ",
   "                                                                                                                                            ",
   "                                                                                                                                            ",
   "                                                                                                                                         #^ ",
   " @      s         $          s        $         s         $          s                  s                   s        $        xxxxxxxxxxxxxx",
   "xxxxxxxxx       xxxxxx       x      xxxxx       x        xxxx        x      xx          x       xx          x      xxxxx      x             ",
   "xxxxxxxxx       xxxxxx       x      xx  xx      x       xxxxxx       x      xx          x       xx          x      xxxxxx     x             ",
   "xxxxxxxxx         xx         x      xx xx       x       xx  xx       x      xx          x       xx          x      xx  xx     x             ",
   "xxxxxxxxx         xx         x      xxxx        x       xx  xx       x      xx $        x       xx $        x      xx  xx     x             ",
   "xxxxxxxxx         xx         x      xx xx       x       xxxxxx       x      xxxxxx      x       xxxxxx      x      xxxxxx     x             ",
   "xxxxxxxxx         xx         x      xx  xx      x        xxxx        x      xxxxxx      x       xxxxxx      x      xxxxx      x             ",
   "xxxxxxxxx                    x                  x                    x                  x                   x                 x             ",
   "xxxxxxxxx                    x                  x                    x                  x                   x                 x             ",
   "xxxxxxxxx                    x                  x                    x                  x                   x                 x             ",
   "xxxxxxxxxx!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!"],
	
  ["              xx                         |                                x       x                                                               ",
   "              xx                                                          x       x                                                               ",
   "              xx                                                          x       x                                                               ",
   "              xx                                                          x       x                                                               ",
   "              xx                                         o      o         x      ox                                                               ",
   "              xx                                                          x       x                                                               ",
   "            xxxxxx                                       x      x         x     xxx                                                               ",
   "            xxxxxx                                       x!!!!!!x         x       x                                                               ",
   "                                                         x!!!!!!x        oxo      x                                                               ",
   "            o    o             xxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxx     x       x                                                               ",
   " @                          xxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx     x                                                               ",
   "xxxxx      xxxxxxxx      xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxx             x                                                               ",
   "xxxx!!!!!!!!xxxxxx!!!!!!!!xxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxx         | xxxxx                                                             ",
   "xxxx!!!!!!!!xxxxxx!!!!!!!!xxxxxxxxxxxxxx   xxxx  |                              x                                                                 ",
   "xxxx!!!!!!!!xxxxxx!!!!!!!xxxxxxxxxxxxxx    xxxxo                         $      x      s                                                          ",
   "xxxx!!!!!!!!xxxxxx!!!!!!xxxxxxxxxxxxxxx    xxxx        xxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxx                                                         ",
   "xxxxxx!!!!!!xxxxxx!!!!!xxxxxxxxxxxxxxxx    xxxxo                       o        x    xxx!!                                             xxxxxxxxxxx",
   "xxxxxx!!!!!!xxxxxx!!!!xxxxxxxxxxxxxxxxx   xxxxx     |        o                 ox    xxxx!!!                                                     x",
   "xxxxxxxx!!!!xxxxxx!!!xxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxx  xxx       xxx     xxx    xxxx!!!!                                                    x",
   "xxxxxxxx!!!!xxxxxx!!!xxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxx                      xx   xxxx!!!!                                                  $ x",
   "xxxxxx!!!!!!xxxxxx!!!!xxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxx     xxx    o         x    xxxx!!!!                                                 xxxx",
   "xxxxxx!!!!!!xxxxxx!!!!!xxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxo          xxx        x    xxxx!!!!!                                                   x",
   "xxxx!!!!!!!!xxxxxx!!!!!!xxxxxxxxxxxxxxx           o o xxxxxx               xxx  x   xxxxx!!!!!                                            #^     x",
   "xxxx!!!!!!!!xxxxxx!!!!!!!xxxxxxxxxxxxxx |          o  xxxx    xxx      o             xxxx!!!!!!                                 xxxx     xxxxxxxxx",
   "xx!!!!!!!!!!xxxxxx!!!!!!!!xxxxxxxxxxxxx xxx       o o xxxx=            x            =xxxx!!!!!!!                         o      x                x",
   "xx!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxxxxxxx    x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!                              x                x",
   "!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxxxxxxx     xx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!                   xxx     x                x",
   "!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxxxxxxx         |     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!           xxx     x                x",
   "!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     x                x",
   "!!!!!!!!!!!!xxxxxx!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!x!!!!!!!!!!!!!!!!x"],
	
   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxx                                                      xxxxxx",
	"xxx                                                            xxx",
	"xx                                                              xx",
	"xx     xx  xx    xxxx    xx  xx      x    x  xxxxxx  xx  xx     xx",
	"xx     xx  xx   xxxxxx   xx  xx      x xx x  xxxxxx  xxx xx     xx",
	"x      xxxxxx   xx  xx   xx  xx      x xx x    xx    xxxxxx      x",
	"x@      xxxx    xx  xx   xx  xx      xxxxxx    xx    xxxxxx      x",
	"xx       xx     xxxxxx   xxxxxx      xx  xx  xxxxxx  xx xxx     xx",
	"xx       xx      xxxx     xxxx        x  x   xxxxxx  xx  xx     xx",
	"xx                                                              xx",
	"xxx                                                         #^ xxx",
	"xxxxxx                                                      xxxxxx",
	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
	
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x           s                                    xxxxx #^    x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
	
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o      x!x  ",
   "                                                xx!x         x     o   o                                 #^ xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
	
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x       #^ x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
	
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                   #^           x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "    xxxx                                                 xx     xx                                            ",
   "    x  x     xxx         xxx         xxx                                 x                  x                 ",
   "    x  x                                                                                                      ",
   "    x  x                                                         ||                                           ",
   "  xxx  xxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
